### ISSUE TITLE
[BUG] Mystical Agriculture Seed Reprocessor cannot accept item input

### ISSUE THREAD

**Issue by finleyaubin** [TeamAOF/All-of-Fabric-6#282] opened 2023-07-02 21:02 UTC
## Description
The Seed Reprocessor from Mystical Agriculture at any tier cannot accept external item inputs from pipes or hoppers from any side, and also you cannot shift click seeds into the correct slot, however, if you place the seeds into the slot, it will work, this makes it impossible to automate.

## To Reproduce
Place a hopper above the Seed Reprocessor facing into it and fill it with inferium seeds, and observe that they are not transferred into the Seed Reprocessor

## Expected behavior
The Inferium seeds are accepted into the input slot in the Seed Reprocessor.

## Priority
Medium

## Screenshots/Video
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/73884515/0a72f5dc-adac-4ee1-8f5f-c74543f8d3ca)

## Affected Version
1.7.1

**Comment by jjs98** [comment] 2023-07-07 18:47
Fixed with new version of MAR [MysticalAgriculture-Refabricated-1.19.2-2.0.6.jar](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture-refabricated/files/4599590)

Maybe an update is possible.

**Comment by Kazuhiko-Gushiken** [comment] 2023-07-07 18:58
@jjs98 wait really? damn. i added a new seed reprocessor for nothing then!

**Comment by Kazuhiko-Gushiken** [comment] 2023-07-07 19:00
wait no, that's version 2.0.6 it seems. the modpack is on 2.0.8. we're past the update and its currently broken again

**Comment by jjs98** [comment] 2023-07-07 19:14
Dont we use 2.0.5? :o

**Comment by jjs98** [comment] 2023-07-07 19:17
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/47151759/e559df9a-147e-4bb0-bf7d-4975d31e75f7)
AOF6 uses 2.0.5

**Comment by Kazuhiko-Gushiken** [comment] 2023-07-07 19:40
oh shit i looked at the wrong thing sorry!

**Comment by jjs98** [comment] 2023-07-07 20:34
So I forked the Modpack and updated the Mod to the newest version and everything worked fine.
Input items via the sides or with shift click works as expacted. The other mashines worked as well.
![image](https://github.com/TeamAOF/All-of-Fabric-6/assets/47151759/b19ae5fa-6e93-47e0-8ac9-740d2ed4aaa0)

**Closed** 2023-07-11 18:34 UTC
Labels: Reopen If Still An Issue

**Comment by tannisroot** [comment] 2023-08-08 11:26
This should be re-opened, the issue is still present @ImAK9
