### ISSUE TITLE
create deployer crash server after using it to fuel blaze burner with lava bucket

### ISSUE THREAD

**Issue by D3DK3T** [TeamAOF/All-of-Fabric-6#147] opened 2023-03-14 16:36 UTC
[crash-2023-03-14_17.24.25-server.txt](https://github.com/TeamAOF/All-of-Fabric-6/files/10981268/crash-2023-03-14_17.24.25-server.txt)

steps to reproduce:
1) build boiler
2) place blaze burner under it
3) automate it with deployer
4) wait for deployer to use second bucket
5) server crash
if you need any additional info contact me with email: jonatan98@o2.pl

**Comment by jpenilla** [comment] 2023-03-24 03:18
duplicate of #133

**Closed** 2023-07-11 18:37 UTC
Labels: Reopen If Still An Issue
